name: release build
on:
  workflow_dispatch:
    inputs:
      version:
        description: "Tag version to release"
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        jobs:
          - { goos: android, goarch: '386', ndk: i686-linux-android34, output: '386' }
          - { goos: android, goarch: amd64, ndk: x86_64-linux-android34, output: amd64 }
          - { goos: android, goarch: arm, ndk: armv7a-linux-androideabi34, output: armv7 }
          - { goos: android, goarch: arm64, ndk: aarch64-linux-android34, output: arm64 }

    steps:
    - uses: actions/checkout@v4
      with:
        repository: tailscale/tailscale